export const RENDER_PLAYLIST = "RENDER_PLAYLIST";
export const PLAYLIST_SUCCESS = "PLAYLIST_SUCCESS";
export const PLAYLIST_FAILURE = "PLAYLIST_FAILURE";
export const SPOTIFY_UPLOAD = "SPOTIFY_UPLOAD";
export const APPLE_UPLOAD = "APPLE_UPLOAD";
export const DEEZER_UPLOAD = "DEEZER_UPLOAD";
